### ISSUE TITLE
Provide access to Datums associated with Sprites in HitTestResults

### ISSUE THREAD

**Issue by RyanMullins** [PAIR-code/megaplot#10]
[LIT](https://github.com/PAIR-code/lit) uses a coordinated, linked visualization architecture to coordinate selection, comparison, and hover states across the app, shown below. 

<img width="1783" alt="Screen Shot 2022-05-10 at 12 04 10 PM" src="https://user-images.githubusercontent.com/868555/167676892-92bd6704-7041-420a-8e3d-fe1882342ef9.png">

Currently, MegaPlot supports inbound traffic in this architecture well, i.e., a values changes in one of those services and I can update a MegaPlot Scene correctly by rebinding dat to a Selection. 

It does not seem possible to support outbound traffic in this architecture given MegaPlot's current implementation, i.e., reacting to a pointer event on the Scene's `<canvas>` or `container`, correlating the Sprites returned from the `.hitTest()`, and pushing those changes to LIT's services. 

I can easily implement `.hitTest()` handlers in response to various pointer events, see #6 and [debugging demo](https://github.com/PAIR-code/megaplot/blob/main/src/demo/debugging-demo.ts#L286). However, the [`HitTestResults`](https://github.com/PAIR-code/megaplot/blob/main/src/lib/hit-test-types.d.ts#L60) and [`Sprite`](https://github.com/PAIR-code/megaplot/blob/main/src/lib/sprite.d.ts#L70) interfaces do not provide a mechanism to correlate a `Sprite` back to associated `datum` from the call to `Selection.bind()`. 

I found some red herrings in the code related to the [`SpriteImpl`'s internal properties](https://github.com/PAIR-code/megaplot/blob/main/src/lib/sprite-impl-properties.ts#L32), which has an `index` that approximately correlates to input order but isn't guaranteed to maintain that correlation so likely isn't a viable solution. 

It looks like this capability is blocked until there is a Selection level `.hitTest()` implementation (see #7) so that the Selection can do the association from its Sprites to the datums.

**Comment by jimbojw** [comment]
I believe PR #21 implements this. Here's an example which uses a `Set` to keep track of which elements are hovered on `mousemove`.

```ts
// Setup.
interface Datum {
  color: [number, number, number, number];  // RGBA.
}
const hoverColor = [0, 0, 0, 1];  // Black.
const container = d3.select('body').node() as HTMLElement;
const scene = new Scene({container});
const selection = scene.createSelection<Datum>();

const data: Datum[] = [
  {color: [255, 0, 0, 1]},  // Red.
  {color: [0, 255, 0, 1]},  // Green.
  {color: [0, 0, 255, 1]},  // Blue.
];

let hoveredData = new Set<Datum>();

selection.onBind((s: SpriteView, d: Datum) => {
  // Set position, size, etc. here...

  // Set fill color based on whether it's hovered.
  s.FillColor = hoveredData.has(d) ? hoverColor : s.color;
});

// Initial bind.
selection.bind();

container.addEventListener('mousemove', ({x, y}: MouseEvent) => {
  const results = selection.hitTest({x, y});
  hoveredIndices = new Set(results);
  selection.bind();
});
```

I have not tested the above, it may contain bugs. A more complete example is available in the debugging demo: https://github.com/PAIR-code/megaplot/blob/dev/src/demo/debugging-demo.ts
